-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.app_versions (
  id integer NOT NULL DEFAULT nextval('app_versions_id_seq'::regclass),
  version character varying NOT NULL UNIQUE CHECK (version::text ~ '^\d+\.\d+\.\d+$'::text),
  release_date timestamp without time zone NOT NULL DEFAULT now(),
  is_latest boolean NOT NULL DEFAULT false,
  is_mandatory boolean NOT NULL DEFAULT false,
  download_url text NOT NULL,
  file_size_mb numeric,
  release_notes text,
  min_version character varying,
  created_by character varying,
  is_active boolean NOT NULL DEFAULT true,
  downloads_count integer DEFAULT 0,
  changelog jsonb,
  CONSTRAINT app_versions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_log (
  id integer NOT NULL DEFAULT nextval('audit_log_id_seq'::regclass),
  user_id integer,
  table_name character varying,
  action character varying,
  record_id integer,
  old_values jsonb,
  new_values jsonb,
  ip_address character varying,
  user_agent text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.invoice_audit (
  id integer NOT NULL DEFAULT nextval('invoice_audit_id_seq'::regclass),
  invoice_id integer,
  action character varying,
  old_values jsonb,
  new_values jsonb,
  user_id integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT invoice_audit_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_audit_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.invoice_status (
  f_invoicestat integer NOT NULL DEFAULT nextval('invoice_status_f_invoicestat_seq'::regclass),
  f_name character varying NOT NULL,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT invoice_status_pkey PRIMARY KEY (f_invoicestat)
);
CREATE TABLE public.order_gastos_indirectos (
  id integer NOT NULL DEFAULT nextval('order_gastos_indirectos_id_seq'::regclass),
  f_order integer NOT NULL,
  monto numeric NOT NULL,
  descripcion character varying NOT NULL,
  fecha_gasto timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_by integer,
  updated_at timestamp without time zone,
  updated_by integer,
  CONSTRAINT order_gastos_indirectos_pkey PRIMARY KEY (id),
  CONSTRAINT order_gastos_indirectos_f_order_fkey FOREIGN KEY (f_order) REFERENCES public.t_order(f_order)
);
CREATE TABLE public.order_gastos_operativos (
  id integer NOT NULL DEFAULT nextval('order_gastos_operativos_id_seq'::regclass),
  f_order integer NOT NULL,
  monto numeric NOT NULL DEFAULT 0,
  descripcion character varying NOT NULL,
  categoria character varying,
  fecha_gasto timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_by integer,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_by integer,
  f_commission_rate numeric DEFAULT 0,
  CONSTRAINT order_gastos_operativos_pkey PRIMARY KEY (id),
  CONSTRAINT order_gastos_operativos_f_order_fkey FOREIGN KEY (f_order) REFERENCES public.t_order(f_order)
);
CREATE TABLE public.order_history (
  id integer NOT NULL DEFAULT nextval('order_history_id_seq'::regclass),
  order_id integer NOT NULL,
  user_id integer NOT NULL,
  action character varying NOT NULL,
  field_name character varying,
  old_value text,
  new_value text,
  change_description text,
  ip_address character varying,
  changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT order_history_pkey PRIMARY KEY (id),
  CONSTRAINT order_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.t_order(f_order),
  CONSTRAINT order_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.order_status (
  f_orderstatus integer NOT NULL DEFAULT nextval('order_status_f_orderstatus_seq'::regclass),
  f_name character varying NOT NULL,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT order_status_pkey PRIMARY KEY (f_orderstatus)
);
CREATE TABLE public.t_attendance (
  id integer NOT NULL DEFAULT nextval('t_attendance_id_seq'::regclass),
  employee_id integer NOT NULL,
  attendance_date date NOT NULL,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['ASISTENCIA'::character varying, 'RETARDO'::character varying, 'FALTA'::character varying, 'VACACIONES'::character varying, 'FERIADO'::character varying, 'DESCANSO'::character varying]::text[])),
  check_in_time time without time zone,
  check_out_time time without time zone,
  late_minutes integer DEFAULT 0,
  notes text,
  is_justified boolean DEFAULT false,
  justification text,
  created_by integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_by integer,
  updated_at timestamp without time zone,
  CONSTRAINT t_attendance_pkey PRIMARY KEY (id),
  CONSTRAINT t_attendance_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.t_payroll(f_payroll)
);
CREATE TABLE public.t_attendance_audit (
  id integer NOT NULL DEFAULT nextval('t_attendance_audit_id_seq'::regclass),
  attendance_id integer NOT NULL,
  employee_id integer NOT NULL,
  attendance_date date NOT NULL,
  action character varying NOT NULL CHECK (action::text = ANY (ARRAY['INSERT'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying]::text[])),
  old_status character varying,
  old_check_in_time time without time zone,
  old_check_out_time time without time zone,
  old_late_minutes integer,
  old_notes text,
  old_is_justified boolean,
  new_status character varying,
  new_check_in_time time without time zone,
  new_check_out_time time without time zone,
  new_late_minutes integer,
  new_notes text,
  new_is_justified boolean,
  changed_by integer,
  changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  ip_address inet,
  user_agent text,
  change_reason text,
  CONSTRAINT t_attendance_audit_pkey PRIMARY KEY (id)
);
CREATE TABLE public.t_balance_adjustments (
  id integer NOT NULL DEFAULT nextval('t_balance_adjustments_id_seq'::regclass),
  year integer NOT NULL,
  month integer NOT NULL,
  adjustment_type character varying,
  original_amount numeric,
  adjusted_amount numeric,
  difference numeric,
  reason text,
  created_by integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT t_balance_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT t_balance_adjustments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.t_client (
  f_client integer NOT NULL DEFAULT nextval('t_client_f_client_seq'::regclass),
  f_name character varying NOT NULL,
  f_address1 character varying,
  f_address2 character varying,
  f_credit integer DEFAULT 0,
  tax_id character varying,
  phone character varying,
  email character varying,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_by integer,
  updated_by integer,
  CONSTRAINT t_client_pkey PRIMARY KEY (f_client),
  CONSTRAINT t_client_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT t_client_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.t_commission_rate_history (
  id integer NOT NULL DEFAULT nextval('t_commission_rate_history_id_seq'::regclass),
  order_id integer NOT NULL,
  vendor_id integer NOT NULL,
  commission_payment_id integer,
  old_rate numeric NOT NULL,
  old_amount numeric NOT NULL,
  new_rate numeric NOT NULL,
  new_amount numeric NOT NULL,
  order_subtotal numeric,
  order_number character varying,
  vendor_name character varying,
  changed_by integer NOT NULL,
  changed_by_name character varying,
  changed_at timestamp without time zone DEFAULT now(),
  change_reason text,
  ip_address character varying,
  is_vendor_removal boolean DEFAULT false,
  CONSTRAINT t_commission_rate_history_pkey PRIMARY KEY (id),
  CONSTRAINT t_commission_rate_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.t_order(f_order),
  CONSTRAINT t_commission_rate_history_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.t_vendor(f_vendor),
  CONSTRAINT t_commission_rate_history_commission_payment_id_fkey FOREIGN KEY (commission_payment_id) REFERENCES public.t_vendor_commission_payment(id)
);
CREATE TABLE public.t_contact (
  f_contact integer NOT NULL DEFAULT nextval('t_contact_f_contact_seq'::regclass),
  f_client integer,
  f_contactname character varying,
  f_email character varying,
  f_phone character varying,
  position character varying,
  is_primary boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT t_contact_pkey PRIMARY KEY (f_contact),
  CONSTRAINT t_contact_f_client_fkey FOREIGN KEY (f_client) REFERENCES public.t_client(f_client)
);
CREATE TABLE public.t_expense (
  f_expense integer NOT NULL DEFAULT nextval('t_expense_f_expense_seq'::regclass),
  f_supplier integer,
  f_description character varying,
  f_expensedate date,
  f_totalexpense numeric DEFAULT 0,
  f_status character varying,
  f_paiddate date,
  f_paymethod character varying,
  f_order integer,
  expense_category character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_by integer,
  f_scheduleddate date,
  CONSTRAINT t_expense_pkey PRIMARY KEY (f_expense),
  CONSTRAINT t_expense_f_supplier_fkey FOREIGN KEY (f_supplier) REFERENCES public.t_supplier(f_supplier),
  CONSTRAINT t_expense_f_order_fkey FOREIGN KEY (f_order) REFERENCES public.t_order(f_order),
  CONSTRAINT t_expense_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.t_fixed_expenses (
  id integer NOT NULL DEFAULT nextval('t_fixed_expenses_id_seq'::regclass),
  expense_type character varying NOT NULL,
  description character varying,
  monthly_amount numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_by integer,
  effective_date date DEFAULT CURRENT_DATE,
  CONSTRAINT t_fixed_expenses_pkey PRIMARY KEY (id),
  CONSTRAINT t_fixed_expenses_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.t_fixed_expenses_history (
  id integer NOT NULL DEFAULT nextval('t_fixed_expenses_history_id_seq'::regclass),
  expense_id integer,
  description character varying,
  monthly_amount numeric,
  effective_date date NOT NULL,
  change_type character varying,
  change_summary text,
  created_by integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT t_fixed_expenses_history_pkey PRIMARY KEY (id),
  CONSTRAINT t_fixed_expenses_history_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES public.t_fixed_expenses(id),
  CONSTRAINT t_fixed_expenses_history_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.t_holiday (
  id integer NOT NULL DEFAULT nextval('t_holiday_id_seq'::regclass),
  holiday_date date NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  is_mandatory boolean DEFAULT true,
  is_recurring boolean DEFAULT true,
  recurring_month integer,
  recurring_day integer,
  recurring_rule character varying,
  year integer,
  created_by integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_by integer,
  updated_at timestamp without time zone,
  CONSTRAINT t_holiday_pkey PRIMARY KEY (id)
);
CREATE TABLE public.t_invoice (
  f_invoice integer NOT NULL DEFAULT nextval('t_invoice_f_invoice_seq'::regclass),
  f_order integer,
  f_folio character varying,
  f_invoicedate date,
  f_receptiondate date,
  f_subtotal numeric DEFAULT 0,
  f_total numeric DEFAULT 0,
  f_downpayment character varying,
  f_invoicestat integer,
  f_paymentdate date,
  due_date date,
  payment_method character varying,
  payment_reference character varying,
  balance_due numeric,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_by integer,
  CONSTRAINT t_invoice_pkey PRIMARY KEY (f_invoice),
  CONSTRAINT t_invoice_f_order_fkey FOREIGN KEY (f_order) REFERENCES public.t_order(f_order),
  CONSTRAINT t_invoice_f_invoicestat_fkey FOREIGN KEY (f_invoicestat) REFERENCES public.invoice_status(f_invoicestat),
  CONSTRAINT t_invoice_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.t_order (
  f_order integer NOT NULL DEFAULT nextval('t_order_f_order_seq'::regclass),
  f_client integer,
  f_contact integer,
  f_quote character varying,
  f_po character varying,
  f_podate date,
  f_estdelivery date,
  f_description character varying,
  f_salesubtotal numeric DEFAULT 0,
  f_saletotal numeric DEFAULT 0,
  f_orderstat integer DEFAULT 0,
  f_expense numeric DEFAULT 0,
  actual_delivery date,
  profit_amount numeric DEFAULT (f_saletotal - f_expense),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_by integer,
  progress_percentage integer DEFAULT 0 CHECK (progress_percentage >= 0 AND progress_percentage <= 100),
  order_percentage integer DEFAULT 0 CHECK (order_percentage >= 0 AND order_percentage <= 100),
  invoiced boolean DEFAULT false,
  last_invoice_date date,
  f_salesman integer,
  updated_by integer,
  f_commission_rate numeric DEFAULT 0,
  gasto_operativo numeric DEFAULT 0,
  gasto_indirecto numeric DEFAULT 0,
  CONSTRAINT t_order_pkey PRIMARY KEY (f_order),
  CONSTRAINT t_order_f_client_fkey FOREIGN KEY (f_client) REFERENCES public.t_client(f_client),
  CONSTRAINT t_order_f_contact_fkey FOREIGN KEY (f_contact) REFERENCES public.t_contact(f_contact),
  CONSTRAINT t_order_f_orderstat_fkey FOREIGN KEY (f_orderstat) REFERENCES public.order_status(f_orderstatus),
  CONSTRAINT t_order_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT t_order_f_salesman_fkey FOREIGN KEY (f_salesman) REFERENCES public.t_vendor(f_vendor),
  CONSTRAINT t_order_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.t_order_deleted (
  id integer NOT NULL DEFAULT nextval('t_order_deleted_id_seq'::regclass),
  original_order_id integer NOT NULL,
  f_po character varying,
  f_quote character varying,
  f_client integer,
  f_contact integer,
  f_salesman integer,
  f_podate date,
  f_estdelivery date,
  f_description text,
  f_salesubtotal numeric,
  f_saletotal numeric,
  f_orderstat integer,
  f_expense numeric,
  progress_percentage integer,
  order_percentage integer,
  f_commission_rate numeric,
  deleted_by integer NOT NULL,
  deleted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  deletion_reason text,
  full_order_snapshot jsonb,
  CONSTRAINT t_order_deleted_pkey PRIMARY KEY (id)
);
CREATE TABLE public.t_overtime_hours (
  id integer NOT NULL DEFAULT nextval('t_overtime_hours_id_seq'::regclass),
  year integer NOT NULL,
  month integer NOT NULL,
  amount numeric DEFAULT 0,
  notes text,
  created_by integer,
  updated_by integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT t_overtime_hours_pkey PRIMARY KEY (id),
  CONSTRAINT t_overtime_hours_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT t_overtime_hours_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.t_overtime_hours_audit (
  id integer NOT NULL DEFAULT nextval('t_overtime_hours_audit_id_seq'::regclass),
  overtime_id integer NOT NULL,
  year integer NOT NULL,
  month integer NOT NULL,
  old_amount numeric,
  new_amount numeric,
  change_type character varying,
  change_reason text,
  changed_by integer,
  changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  ip_address character varying,
  user_agent text,
  CONSTRAINT t_overtime_hours_audit_pkey PRIMARY KEY (id),
  CONSTRAINT t_overtime_hours_audit_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id)
);
CREATE TABLE public.t_payroll (
  f_payroll integer NOT NULL DEFAULT nextval('t_payroll_f_payroll_seq'::regclass),
  f_employee character varying,
  f_title character varying,
  f_hireddate date,
  f_range character varying,
  f_condition character varying,
  f_lastraise date,
  f_sspayroll numeric DEFAULT 0,
  f_weeklypayroll numeric DEFAULT 0,
  f_socialsecurity numeric DEFAULT 0,
  f_benefits character varying,
  f_benefitsamount numeric DEFAULT 0,
  f_monthlypayroll numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  employee_code character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_by integer,
  created_by integer,
  CONSTRAINT t_payroll_pkey PRIMARY KEY (f_payroll),
  CONSTRAINT t_payroll_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT t_payroll_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.t_payroll_history (
  id integer NOT NULL DEFAULT nextval('t_payroll_history_id_seq'::regclass),
  f_payroll integer,
  f_employee character varying,
  f_title character varying,
  f_hireddate date,
  f_range character varying,
  f_condition character varying,
  f_lastraise date,
  f_sspayroll numeric,
  f_weeklypayroll numeric,
  f_socialsecurity numeric,
  f_benefits character varying,
  f_benefitsamount numeric,
  f_monthlypayroll numeric,
  employee_code character varying,
  is_active boolean,
  changed_fields jsonb,
  effective_date date NOT NULL,
  change_type character varying,
  change_summary text,
  created_by integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT t_payroll_history_pkey PRIMARY KEY (id),
  CONSTRAINT t_payroll_history_f_payroll_fkey FOREIGN KEY (f_payroll) REFERENCES public.t_payroll(f_payroll),
  CONSTRAINT t_payroll_history_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.t_payrollovertime (
  f_payrollovertime integer NOT NULL DEFAULT nextval('t_payrollovertime_f_payrollovertime_seq'::regclass),
  f_date date,
  f_payroll numeric DEFAULT 0,
  f_overtime numeric DEFAULT 0,
  f_fixedexpense numeric DEFAULT 0,
  f_estimate integer DEFAULT 0,
  employee_id integer,
  hours_worked numeric,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_by integer,
  CONSTRAINT t_payrollovertime_pkey PRIMARY KEY (f_payrollovertime),
  CONSTRAINT t_payrollovertime_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.t_payroll(f_payroll),
  CONSTRAINT t_payrollovertime_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.t_supplier (
  f_supplier integer NOT NULL DEFAULT nextval('t_supplier_f_supplier_seq'::regclass),
  f_suppliername character varying NOT NULL,
  f_credit integer DEFAULT 0,
  tax_id character varying,
  phone character varying,
  email character varying,
  address text,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT t_supplier_pkey PRIMARY KEY (f_supplier)
);
CREATE TABLE public.t_vacation (
  id integer NOT NULL DEFAULT nextval('t_vacation_id_seq'::regclass),
  employee_id integer NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  total_days integer DEFAULT ((end_date - start_date) + 1),
  notes text,
  status character varying DEFAULT 'PENDIENTE'::character varying CHECK (status::text = ANY (ARRAY['PENDIENTE'::character varying, 'APROBADA'::character varying, 'RECHAZADA'::character varying, 'CANCELADA'::character varying]::text[])),
  approved_by integer,
  approved_at timestamp without time zone,
  rejection_reason text,
  created_by integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_by integer,
  updated_at timestamp without time zone,
  CONSTRAINT t_vacation_pkey PRIMARY KEY (id),
  CONSTRAINT t_vacation_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.t_payroll(f_payroll)
);
CREATE TABLE public.t_vacation_audit (
  id integer NOT NULL DEFAULT nextval('t_vacation_audit_id_seq'::regclass),
  vacation_id integer NOT NULL,
  employee_id integer NOT NULL,
  action character varying NOT NULL CHECK (action::text = ANY (ARRAY['INSERT'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying]::text[])),
  old_start_date date,
  old_end_date date,
  old_status character varying,
  old_notes text,
  new_start_date date,
  new_end_date date,
  new_status character varying,
  new_notes text,
  changed_by integer,
  changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  change_reason text,
  CONSTRAINT t_vacation_audit_pkey PRIMARY KEY (id)
);
CREATE TABLE public.t_vendor (
  f_vendor integer NOT NULL DEFAULT nextval('t_vendor_f_vendor_seq'::regclass),
  f_vendorname character varying NOT NULL,
  f_user_id integer,
  f_commission_rate numeric DEFAULT 0,
  f_phone character varying,
  f_email character varying,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT t_vendor_pkey PRIMARY KEY (f_vendor),
  CONSTRAINT t_vendor_f_user_id_fkey FOREIGN KEY (f_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.t_vendor_commission_payment (
  id integer NOT NULL DEFAULT nextval('t_vendor_commission_payment_id_seq'::regclass),
  f_order integer NOT NULL,
  f_vendor integer NOT NULL,
  commission_amount numeric NOT NULL DEFAULT 0,
  commission_rate numeric NOT NULL,
  payment_status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (payment_status::text = ANY (ARRAY['draft'::character varying::text, 'pending'::character varying::text, 'paid'::character varying::text])),
  payment_date date,
  payment_reference character varying,
  notes text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_by integer,
  updated_by integer,
  CONSTRAINT t_vendor_commission_payment_pkey PRIMARY KEY (id),
  CONSTRAINT fk_commission_order FOREIGN KEY (f_order) REFERENCES public.t_order(f_order),
  CONSTRAINT fk_commission_vendor FOREIGN KEY (f_vendor) REFERENCES public.t_vendor(f_vendor),
  CONSTRAINT fk_commission_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_commission_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.t_workday_config (
  id integer NOT NULL DEFAULT nextval('t_workday_config_id_seq'::regclass),
  day_of_week integer NOT NULL UNIQUE CHECK (day_of_week >= 0 AND day_of_week <= 6),
  is_workday boolean DEFAULT true,
  description character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  CONSTRAINT t_workday_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  username character varying NOT NULL UNIQUE,
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  full_name character varying NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['direccion'::character varying, 'administracion'::character varying, 'proyectos'::character varying, 'coordinacion'::character varying, 'ventas'::character varying]::text[])),
  is_active boolean DEFAULT true,
  last_login timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);